openapi: 3.1.0
info:
  title: Command Registry Interface
  description: Internal contract for AI command registration and execution within Logseq plugin
  version: 1.0.0

paths:
  /commands/register:
    post:
      summary: Register new AI command
      description: Register built-in or custom command in the plugin registry
      operationId: registerCommand
      tags:
        - Commands
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AICommand'
            examples:
              builtInCommand:
                summary: Built-in Ask AI command
                value:
                  id: ask-ai
                  title: Ask AI
                  description: Ask AI a question without context
                  promptTemplate: "{question}"
                  requiresInput: true
                  requiresSelection: false
                  contextStrategy: none
                  modelOverride: null
                  temperatureOverride: null
                  isCustom: false
                  menuContext:
                    - palette
                    - toolbar
                    - slash

              customCommand:
                summary: Custom translation command
                value:
                  id: custom-block-uuid-123
                  title: Translate to English
                  description: Custom command
                  promptTemplate: "Translate the following to English:\n{content}"
                  requiresInput: false
                  requiresSelection: true
                  contextStrategy: selection
                  modelOverride: gpt-4
                  temperatureOverride: null
                  isCustom: true
                  menuContext:
                    - context-menu
                    - palette

      responses:
        '200':
          description: Command registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  commandId:
                    type: string
                    example: ask-ai

        '400':
          description: Invalid command definition
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /commands/execute:
    post:
      summary: Execute AI command
      description: Execute registered command with optional user input and target block
      operationId: executeCommand
      tags:
        - Commands
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExecutionRequest'
            examples:
              basicQuestion:
                summary: Execute Ask AI with question
                value:
                  commandId: ask-ai
                  userInput: What is Logseq?
                  targetBlockUUID: block-uuid-789
                  triggerSource: palette

              summarizePage:
                summary: Summarize current page
                value:
                  commandId: summarize-page
                  userInput: null
                  targetBlockUUID: null
                  triggerSource: slash

      responses:
        '202':
          description: Command execution started
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExecutionResponse'

        '400':
          description: Invalid execution request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

        '404':
          description: Command not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /commands/list:
    get:
      summary: List registered commands
      description: Retrieve all registered commands with optional filtering
      operationId: listCommands
      tags:
        - Commands
      parameters:
        - name: menuContext
          in: query
          description: Filter by menu context
          schema:
            type: string
            enum: [palette, toolbar, context-menu, slash]
        - name: isCustom
          in: query
          description: Filter by custom vs built-in
          schema:
            type: boolean

      responses:
        '200':
          description: List of registered commands
          content:
            application/json:
              schema:
                type: object
                properties:
                  commands:
                    type: array
                    items:
                      $ref: '#/components/schemas/AICommand'
                  totalCount:
                    type: integer

components:
  schemas:
    AICommand:
      type: object
      required:
        - id
        - title
        - promptTemplate
        - requiresInput
        - requiresSelection
        - contextStrategy
        - isCustom
        - menuContext
      properties:
        id:
          type: string
          description: Unique command identifier
          pattern: '^[a-z0-9-]+$'
          example: ask-ai

        title:
          type: string
          description: Display name in UI
          minLength: 1
          maxLength: 50
          example: Ask AI

        description:
          type: string
          description: Tooltip or help text
          maxLength: 200
          example: Ask AI a question without context

        promptTemplate:
          type: string
          description: Template with variables {question}, {context}, {content}
          minLength: 1
          example: "Context:\n{context}\n\nQuestion: {question}"

        requiresInput:
          type: boolean
          description: Whether to prompt user for input before execution
          example: true

        requiresSelection:
          type: boolean
          description: Whether command requires selected block(s)
          example: false

        contextStrategy:
          type: string
          enum: [none, page, block, selection]
          description: How to extract context for LLM request
          example: page

        modelOverride:
          type: string
          description: Specific model to use (overrides settings default)
          nullable: true
          example: gpt-4

        temperatureOverride:
          type: number
          description: Temperature override (0.0-2.0)
          minimum: 0.0
          maximum: 2.0
          nullable: true
          example: 0.8

        isCustom:
          type: boolean
          description: Whether command is user-defined
          example: false

        menuContext:
          type: array
          description: Where command appears in UI
          minItems: 1
          uniqueItems: true
          items:
            type: string
            enum: [palette, toolbar, context-menu, slash]
          example:
            - palette
            - toolbar

    ExecutionRequest:
      type: object
      required:
        - commandId
        - triggerSource
      properties:
        commandId:
          type: string
          description: ID of command to execute
          example: ask-ai

        userInput:
          type: string
          description: User-provided question or input
          nullable: true
          example: What is Logseq?

        targetBlockUUID:
          type: string
          description: UUID of target block for output (null = end of page)
          nullable: true
          example: block-uuid-789

        triggerSource:
          type: string
          enum: [palette, toolbar, context-menu, slash]
          description: How command was invoked
          example: palette

    ExecutionResponse:
      type: object
      required:
        - requestId
        - status
        - placeholderUUID
      properties:
        requestId:
          type: string
          description: Unique request identifier
          example: req-uuid-456

        status:
          type: string
          enum: [pending, streaming, completed, failed, cancelled]
          description: Current execution status
          example: pending

        placeholderUUID:
          type: string
          description: UUID of placeholder block created
          example: block-uuid-890

        estimatedTokens:
          type: integer
          description: Estimated context tokens (if available)
          nullable: true
          example: 2500

    ContextExtraction:
      type: object
      description: Internal representation of extracted context
      required:
        - type
        - content
        - sourceUUIDs
        - estimatedTokens
        - wasTruncated
      properties:
        type:
          type: string
          enum: [page, block, selection, none]
          description: Context extraction strategy used

        content:
          type: string
          description: Extracted text content (may be truncated)

        sourceUUIDs:
          type: array
          description: UUIDs of source blocks/pages
          items:
            type: string

        estimatedTokens:
          type: integer
          description: Token count estimate (chars / 4)
          minimum: 0

        wasTruncated:
          type: boolean
          description: Whether content exceeded max context length

        metadata:
          type: object
          description: Additional context info
          additionalProperties: true
          example:
            pageTitle: Project Alpha
            blockCount: 42

    PropertyOverrides:
      type: object
      description: Block property overrides resolved from hierarchy
      properties:
        blockUUID:
          type: string
          description: UUID of block these properties belong to

        model:
          type: string
          description: Override model name
          nullable: true
          example: qwen2

        temperature:
          type: number
          description: Override temperature
          minimum: 0.0
          maximum: 2.0
          nullable: true
          example: 0.8

        topP:
          type: number
          description: Override top_p
          minimum: 0.0
          maximum: 1.0
          nullable: true
          example: 0.9

        useContext:
          type: boolean
          description: Whether to include context
          nullable: true

        isInherited:
          type: boolean
          description: Whether properties are inherited from ancestors

    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: object
          required:
            - message
            - code
          properties:
            message:
              type: string
              description: Human-readable error message

            code:
              type: string
              description: Error code
              enum:
                - command_not_found
                - invalid_parameters
                - missing_input
                - missing_selection
                - execution_failed

            details:
              type: object
              description: Additional error context
              additionalProperties: true
